### ISSUE TITLE
Integration tests with real MWA data

### ISSUE THREAD

**Issue by adampbeardsley** [HERA-Team/hera_cal#10]
~~FHD/PRISim simulation -> fake gains -> calibrate -> image~~

Real data: MWA hex data - calibrate -> compare with @wenyang-li solutions

**Comment by bhazelton** [comment]
I'm going to split this into 2 separate issues for the two above tests and rename this issue as appropriate.

**Comment by wenyang-li** [comment]
![heracal_mwa_vs_fhd](https://cloud.githubusercontent.com/assets/18742340/26009743/2209e836-3718-11e7-8c27-2122caf1dde6.png)
This is a plot showing a comparison between heracal and FHD on MWA Phase II data. This is one obs id calibration. Upper row shows heracal on MWA hexes and bottom row shows full FHD calibration on the same obs id. Left column shows amplitude calibration and right column shows phase calibration. I used firstcal and omnical from heracal module on the data, then used my own function to fit degeneracy parameters to FHD solution so that I can compare these two sets of solutions.

**Comment by wenyang-li** [comment]
[heracal-tests-mwa.pdf](https://github.com/HERA-Team/hera_cal/files/1107521/heracal-tests-mwa.pdf)
I wrote a memo for heracal on MWA Phase II data. The calibration simulation is still underway. Please let me know if you have any questions. I will keep updating this memo.

**Comment by SaulAryehKohn** [comment]
Awesome!

**Comment by jsdillon** [comment]
This has been stale for a long time and I don't think it's on the critical path for HERA, so I'm going to close this issue.
