### ISSUE TITLE
remove firstcal tip-tilt degeneracy

### ISSUE THREAD

**Issue by nkern** [HERA-Team/hera_cal#113]
firstcal seems to be inserting a tip-tilt solution into raw data. we need a `remove-degen` function to take it out before passing firstcal solutions to omnical.

**Comment by jsdillon** [comment]
Yeah, it turns out we fix the overall average delay to be zero (need to double check that), but we don't fix the tip and tilt in delays (which are also degeneracies of firstcal). Omnical keeps whatever firstcal put in, so this explains a fair bit of why the omnical solutions cause images to wander around.

**Comment by plaplant** [comment]
Naive question: is this more complicated than running the existing `remove-degen` on the firstcal results?

**Comment by nkern** [comment]
5/15/2018 update: we didn't write a firstcal remove-degen. we did write an `abscal` module to correct for any degeneracy firstcal puts in and correctly phase the data
