### ISSUE TITLE
This line of the comment in abscal_func.py is not mathematically correct.

### ISSUE THREAD

**Issue by AaronParsons** [HERA-Team/hera_cal#245]
https://github.com/HERA-Team/hera_cal/blob/eb002532ebc4433683f60756a098518b15e60ea3/hera_cal/abscal_funcs.py#L101

**Comment by nkern** [comment]
you mean because the RHS should read `angle(g_i_x - g_j_y)`? If so thats because thats just a typo in the doc-string (which should be fixed!). if you look in the code you'll see that its actually doing is

`ydata = odict([(k, np.angle(data[k]/model[k])) for k in keys])`

so the LHS of the doc-string is a correct representation of what its doing, and its then equating that to 

`Phi_i * r_i - Phi_j * r_j`, not `angle(g_i_x) * angle(g_j_y)`, which is definitely wrong b/c that's not even a linear system...

**Comment by jsdillon** [comment]
Yeah, it's just that there's an issue in the docstring.

**Comment by jsdillon** [comment]
Addressed in #261.
