### ISSUE TITLE
idr2 cross pol flags

### ISSUE THREAD

**Issue by nkern** [HERA-Team/hera_cal#314]
the cross-pol (i.e. `xy` and `yx`) post-LSTBIN visibility files are completely flagged. The un-LSTbinned cross-pol `uvOCRS` files are also flagged, but their respective `uvOCR` files are not. something seems to be wrong with `apply_cal`

**Comment by jsdillon** [comment]
The issue turned out to be a typo in do_OMNI_APPLY and do_CAL_SMOOTH_APPLY where the apply_cal script was only getting the y gains but not the x gains. This made apply_cal think that all the visibilities had missing gains, which is interpreted as flags (this is because omnical excludes bad antennas from the calibration solutions rather than flagging them). We don't need to rerun do_OMNI_APPLY (since the .xy.*.uvOs are not used for anything), but we do need to rerun:

* smooth cal apply (@plaplant will do that)
* delay filter (@plaplant will do that)
* LST-bin .uvOCRS and .uvOCRSD for one_group, two_group, and three_group (@nkern will do that)

**Comment by jsdillon** [comment]
Although we had to manually flag a couple of files (see #321), @nkern we're now ready to rerun the lst-binning.

**Comment by nkern** [comment]
This is fixed for all data files in 
`/lustre/aoc/projects/hera/H1C_IDR2/IDR2_1/LSTBIN/one_group`
`/lustre/aoc/projects/hera/H1C_IDR2/IDR2_1/LSTBIN/two_group`
`/lustre/aoc/projects/hera/H1C_IDR2/IDR2_1/LSTBIN/three_group`
