### ISSUE TITLE
checking omnical preserves degenerate modes

### ISSUE THREAD

**Issue by nkern** [HERA-Team/hera_cal#316]
At the Sante Fe CHAMP conference (H2C RTP meeting) we discussed the order of omnical / abscal, and @bhazelton mentioned that @wenyang-li found in a simulation that omnical (which GIT hash?) wasn't preserving degenerate modes substantially. This needs some level of investigation for the H2C RTP. @plaplant @AaronParsons @jsdillon

**Comment by wenyang-li** [comment]
I think what I mean was the C code of omnical was not doing degeneracy removal correctly in the phase gradients. I was using https://github.com/AaronParsons/omnical. The script omnical/src/_omnical/omnical_redcal.cc, where the function removeDegen lives, has not been changed since the October of 2015. I think hera_cal is handling the degeneracies right so this is probably not an issue now.

**Comment by jsdillon** [comment]
Can you check @wenyang-li?

**Comment by wenyang-li** [comment]
OK, I will check it. Looks like a lot of things has been changed and I have not pulled hera_cal for a while.

**Comment by wenyang-li** [comment]
I just did the test. The answer is yes, I believe redcal.py does the right thing in degeneracy removal.

I used HERA19 layout, simulated visibilities, then multiplied gains, each of which is set to be 1 + np.random.normal(0, 0.1, nfreq) + 1j*np.random.normal(0, 0.1, nfreq), then ran omnical. I put the solutions into the remove_degen in redcal and saved it (labelled as g1). For the double check, I coded my own way of projecting degeneracy to 1 by fitting a plane in (u , v, gain phase) space then remove the phase gradients and offsets (exactly what I did in MWA PhaseII calibration), and save the solution (labelled as g2). Turns out g1 and g2 are the same (difference level is 1e-8). 

If I plot the antenna phases at a single frequency versus antenna positions, they both give me the same result:
<img width="364" alt="screen shot 2018-06-14 at 6 14 45 am" src="https://user-images.githubusercontent.com/18742340/41381750-c459a088-6f9b-11e8-9901-81c2ef133d12.png">

The statistics of the phases after degeneracy remove over antennas (checked across all frequency channels) is ~0 mean and ~0.1 std, which agree with what I put in (since the gain is close to 1, so the phase part is close to its imaginary part, which has sigma = 0.1). So this means the degeneracy has been removed, otherwise the mean will be non-zeros if phase offset term is non-zero, and the std will be greater than 0.1 if the phase gradients aren't removed correctly.

**Comment by jsdillon** [comment]
Great! Thanks @wenyang-li 

I think we can consider this issue closed. It might be good for you to post the code you used for you test in this thread.

**Comment by wenyang-li** [comment]
Here are the simulated miriad file and ipynb for my test.

[hex19.uv.zip](https://github.com/HERA-Team/hera_cal/files/2107849/hex19.uv.zip)

[degen_test.ipynb.zip](https://github.com/HERA-Team/hera_cal/files/2107850/degen_test.ipynb.zip)
