### ISSUE TITLE
Calibrate omnical visibility solutions further

### ISSUE THREAD

**Issue by adampbeardsley** [HERA-Team/hera_cal#487]

**Comment by Chuneeta** [comment]
The absolute calibration gains are identical for all baselines in redundant group, however the smoothcal gains does not line up for all the redundant baseline. The plot below show the waterfall plot of the smooth cal gains only for all the 14 m East-West redundant antenna pairs.
![smooth_gains_only](https://user-images.githubusercontent.com/8384144/59954990-87df0780-943c-11e9-878b-b5430d31147f.png)

Slices across one timestamp is shown below.
![smooth_gains_only_tslice](https://user-images.githubusercontent.com/8384144/59955018-af35d480-943c-11e9-8146-a785d7fc1acd.png)

We notice a huge discrepancies for baseline (69, 70) -- the red line and (68, 69) --the green line. This discrepancy is due to missing data since a hug chunk of data across time is flagged for antenna 69 and in the future the antenna will be considered as bad and flagged as per @jsdillon. So this should pose great issue for now. However we need to find a way to either account for the solutions for these weird baselines during the smoothing process.
  
Also the small fluctuation that we see in the remaining baselines are mainly due to missing data. Averaging the solutions across all the redundant pairs might be possible solution.
