### ISSUE TITLE
uvw array in model vis file is non-physical

### ISSUE THREAD

**Issue by adampbeardsley** [HERA-Team/hera_cal#98]
For reference, I've copied Chris Carilli's email below:

> I am playing with latest data off HERA, starting from the fits file in:
> zen.2458026.51913.HH.uv.vis.uvfits
> (Oct 3)
> 
> there are 27 antennas in the file. some of the cross correlations are
> missing, but more importantly, attached are two plots of visibility
> amplitude vs. baseline length in meters
> for baselines to one antenna. never mind the details, the point is that:
> 
> the HERA19 data have a minimum baseline of 14m, as expected.
> 
> the new data have a minimum baseline of 9.5m.  that can't be right.
> 
> seems like there is something wrong in the uvw?  the same is true if you
> plot with X axis in
> wavelengths, not m.  the new data seem to have wrong baseline lengths,
> at least when read
> through FITS into CASA.
> 
> I also note that the antenna numbering seems off -- the shortest
> baselines in the new data
> are NOT between two antennas next to each other, at least in terms of
> numbering. need
> to look harder at this.
> 
> cc

![image](https://user-images.githubusercontent.com/4752917/31151747-c89217c2-a84d-11e7-9dc7-dc3d8b2a2886.png)
![image](https://user-images.githubusercontent.com/4752917/31151752-ccf5cf16-a84d-11e7-900a-4ca98d4033f7.png)

**Comment by adampbeardsley** [comment]
I checked an actual data file from the same day, and it looks correct.

**Comment by zakiali** [comment]
I just did a quick look and it probably stems from the fact that when the vis file is written an aipy antenna array is passed along with it for antenna position information. This antenna array is made from a calfile if one is passed in. I'm assuming that the same calfile is being passed into RTP that always has been and if it hasn't been updated in the recent deployment it probably only has the 19 HERA dishes. I may completely wrong on this.... @plaplant Do you know what calfile is being used?

**Comment by plaplant** [comment]
We have transitioned away from calfiles for the current observing season, and instead write the antenna positions into the data files themselves. We then use the `get_aa_from_uv` function in `hera_cal/utils.py` to generate an AntennaArray object from the file. That would be my guess for where to start looking for discrepancies.

Note that the antenna positions in the files are "correct" Miriad-standard conforming: the coordinate system is rotated ECEF (Earth-centered, Earth-fixed coordinates, with the x-axis rotated to intersect with the local meridian), and the antenna coordinates are given in nanoseconds (so converting to meters introduces a factor of ~3). If you want to convert to, say, local topographic coordinates (so antenna coordinates are ~10 m instead of ~6e6 m), you can use the coordinate transformation functions in pyuvdata.

**Comment by plaplant** [comment]
This issue was addressed in fixing the uvw units in #126. Closing this issue.
